# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_schema_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='database',
            old_name='connection_string',
            new_name='dev_connection_string',
        ),
        migrations.AddField(
            model_name='database',
            name='prod_connection_string',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='exist_in_prod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='exist_in_prod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tester.TestType'),
            preserve_default=False,
        ),
    ]
