# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_auto_20160821_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='table',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.AddField(
            model_name='table',
            name='test_script_completeness_source',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='test_script_completeness_target',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='test_script_dev_to_prod_compare',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='test_script_uniqueness',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='test_value_completeness_source',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='test_value_completeness_target',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='test_value_dev_to_prod_compare_dev',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='test_value_dev_to_prod_compare_prod',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='test_value_uniqueness',
            field=models.BigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestType',
        ),
    ]
