# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_auto_20160823_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='test_value_uniqueness',
            new_name='test_value_uniqueness_dev',
        ),
        migrations.AddField(
            model_name='table',
            name='test_value_uniqueness_prod',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='test_script_completeness_source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='test_script_completeness_target',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='test_script_dev_to_prod_compare',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='test_script_uniqueness',
            field=models.TextField(null=True),
        ),
    ]
