# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_auto_20160830_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='script_get_schemas_list',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='script_get_tables_list',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='script_set_active_schema',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='dev_connection_string',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='prod_connection_string',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
